/* ===== ここだけ毎回貼り替える ===== */
/* updateISO  : New判定・相対日付の基準日 (YYYY-MM-DD)        */
/* updateTime : 更新した時刻 (HH:MM)。曜日は自動で付きます      */
/* timetable  : 週の時間割（PDFから3組のみ抽出）。週次で差し替え */
/* items      : 各行のデータ。Claudeが返す塊をそのまま貼る     */

window.CLASSROOM_DATA = {
  updateISO: "2026-09-18",
  updateTime: "09:13",
  /* 2学期の平常時間割（Classroom資料「9月14日～」/ 0914.pdf の3組列を抽出）。木曜は西洋美術館見学/英語ワークショップが
     クラス間でローテーションする特殊日で、3組の割当は資料からの推測（詳細はtt4アイテムのPDFで要確認）。週次で差し替える。 */
  timetable: {
    label: "9/14(月)〜9/18(金)",
    days: [
      {n:'月',md:'9/14',iso:'2026-09-14'},
      {n:'火',md:'9/15',iso:'2026-09-15'},
      {n:'水',md:'9/16',iso:'2026-09-16'},
      {n:'木',md:'9/17',iso:'2026-09-17'},
      {n:'金',md:'9/18',iso:'2026-09-18'},
    ],
    rows: [
      [ {s:'数',t:'森本',r:'HR'},        {s:'ようこそ先輩準備の会',t:'',r:''}, {s:'英語ワークショップ',t:'',r:'',rs:3}, {s:'国立西洋美術館見学',t:'',r:'',rs:6,mk:'※要確認'}, {s:'数',t:'山口',r:'HR'} ],
      [ {s:'体',t:'佐々木・齋藤',r:'プール'}, {s:'英',t:'平岡',r:'HR'},        null,                                    null,                                  {s:'社',t:'平野',r:'HR'} ],
      [ {s:'学活',t:'',r:''},           {s:'国',t:'鈴木',r:'HR'},          null,                                    null,                                  {s:'英',t:'コリンズ・マオ',r:'LL/400'} ],
      [ {s:'英',t:'平岡・本木',r:'HR/405'}, {s:'体',t:'新谷',r:'二体'},       {s:'理',t:'大越・田悟',r:'理科A/D'},       null,                                  {s:'国',t:'鈴木',r:'HR'} ],
      [ {s:'社',t:'宮崎',r:'HR'},        {s:'西洋美術館事前授業(HR)',t:'',r:'',rs:2}, {s:'美',t:'芝',r:'美術室',rs:2},   null,                                  {s:'礼法(大ホール)',t:'',r:'',rs:2,mk:'13:30整列'} ],
      [ {s:'総合',t:'担任',r:'HR'},      null,                                    null,                              null,                                  null ],
    ]
  },
  basketball: {
  "start": "2026-09-01",
  "end": "2026-10-31",
  "events": {
    "2026-09-07": {
      "kind": "off",
      "title": "休校・登校禁止",
      "time": "",
      "place": "",
      "detail": "大雨のため家庭学習。月間表の練習予定より9/7の学校連絡を優先。",
      "source": "保護者メール 9/7"
    },
    "2026-09-09": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-11": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-14": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第2体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-18": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-25": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-28": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第2体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-30": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-02": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-05": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第2体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-07": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-16": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-19": {
      "kind": "practice",
      "title": "練習",
      "time": "時間記載なし",
      "place": "第2体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-12": {
      "kind": "match",
      "title": "練習試合",
      "time": "12:00 準備",
      "place": "本校・第3体育館",
      "detail": "麻生中・田島中との練習試合。原則1・3年生。昼食は11:30〜12:00に3年1組で。早く来すぎないこと。",
      "source": "月間予定表 ＋ バスケ投稿 9/10"
    },
    "2026-09-13": {
      "kind": "uncertain",
      "title": "私学大会？",
      "time": "",
      "place": "場所未定",
      "detail": "月間表は「私学大会？」と記載。開催・参加・時間は未確定。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-16": {
      "kind": "uncertain",
      "title": "練習なし？",
      "time": "",
      "place": "第3体育館",
      "detail": "月間表は「3年目白で学ぶ1日／練習なし？」と記載。1年生の練習有無も確定できません。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-19": {
      "kind": "off",
      "title": "総体・1年生は不参加",
      "time": "",
      "place": "",
      "detail": "川崎市総体1回戦。1年生は「ようこそ先輩」があるため参加できないとの9/10投稿。",
      "source": "バスケ投稿 9/10"
    },
    "2026-09-20": {
      "kind": "match",
      "title": "総体2回戦（勝ち進んだ場合）",
      "time": "7:30 集合",
      "place": "本校正門 → 南菅中",
      "detail": "1回戦に勝った場合。徒歩で移動、8:45試合開始、12:00頃解散予定。月間表の「私学大会？」は未確定。",
      "source": "月間予定表 ＋ バスケ投稿 9/10"
    },
    "2026-09-21": {
      "kind": "uncertain",
      "title": "私学大会（条件付き）",
      "time": "",
      "place": "場所未定",
      "detail": "8/30に勝った場合、この日に試合の可能性大と記載。出場確定情報は未確認。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-23": {
      "kind": "morning",
      "title": "午前練習",
      "time": "8:30〜12:00",
      "place": "第2・3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-26": {
      "kind": "uncertain",
      "title": "総体3回戦／午後練習",
      "time": "練習なら13:00〜16:00",
      "place": "練習：第2・3体育館",
      "detail": "大会の結果次第。負けたら午後練習。大会の会場・集合時刻は記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-09-27": {
      "kind": "uncertain",
      "title": "総体準決勝・決勝",
      "time": "",
      "place": "",
      "detail": "負けた場合はオフ。大会の会場・集合時刻は記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-04": {
      "kind": "match",
      "title": "地区交流会",
      "time": "時間未定",
      "place": "場所未定",
      "detail": "1・2年生の大会。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-08": {
      "kind": "practice",
      "title": "十月祭準備・練習",
      "time": "時間記載なし",
      "place": "",
      "detail": "準備日に練習あり。時間・場所の記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-09": {
      "kind": "practice",
      "title": "十月祭準備・練習",
      "time": "時間記載なし",
      "place": "",
      "detail": "準備日に練習あり。時間・場所の記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-10": {
      "kind": "match",
      "title": "十月祭・部内戦",
      "time": "午前",
      "place": "",
      "detail": "月間表は「AM部内戦」。試合の開始時刻・集合時刻は未記載。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-11": {
      "kind": "match",
      "title": "十月祭・招待試合",
      "time": "午後",
      "place": "",
      "detail": "サレジアン国際世田谷との招待試合。開始時刻・集合時刻は未記載。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-12": {
      "kind": "school",
      "title": "片付け日",
      "time": "",
      "place": "",
      "detail": "練習については記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-13": {
      "kind": "uncertain",
      "title": "午後練習？",
      "time": "予定 13:00〜16:00",
      "place": "第3体育館",
      "detail": "振替休日。「練習する？そもそもできない？？」との備考があり、実施未確定。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-14": {
      "kind": "school",
      "title": "振替休日",
      "time": "",
      "place": "",
      "detail": "練習については記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-17": {
      "kind": "morning",
      "title": "午前練習",
      "time": "8:30〜12:00",
      "place": "第2・3体育館",
      "detail": "",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-20": {
      "kind": "school",
      "title": "テスト1週間前",
      "time": "",
      "place": "",
      "detail": "練習については記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-21": {
      "kind": "uncertain",
      "title": "承諾書提出者は練習",
      "time": "時間記載なし",
      "place": "",
      "detail": "承諾書提出者が対象。場所・時刻は記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-23": {
      "kind": "uncertain",
      "title": "承諾書提出者は練習",
      "time": "時間記載なし",
      "place": "",
      "detail": "承諾書提出者が対象。場所・時刻は記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-24": {
      "kind": "match",
      "title": "新人戦1回戦",
      "time": "時間未定",
      "place": "場所未定",
      "detail": "1・2年生の大会。日程・参加条件は後続の連絡も確認。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-25": {
      "kind": "match",
      "title": "新人戦2回戦",
      "time": "時間未定",
      "place": "場所未定",
      "detail": "1・2年生の大会。日程・参加条件は後続の連絡も確認。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-27": {
      "kind": "school",
      "title": "中間テスト",
      "time": "",
      "place": "",
      "detail": "練習については記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-28": {
      "kind": "school",
      "title": "中間テスト",
      "time": "",
      "place": "",
      "detail": "練習については記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-29": {
      "kind": "school",
      "title": "中間テスト",
      "time": "",
      "place": "",
      "detail": "練習については記載なし。",
      "source": "月間予定表「2026年9-10月.pdf」"
    },
    "2026-10-30": {
      "kind": "practice",
      "title": "テスト後に練習",
      "time": "15:30 最終下校",
      "place": "第3体育館",
      "detail": "昼食持参。中間テスト後に練習あり。",
      "source": "月間予定表「2026年9-10月.pdf」"
    }
  }
},
  items: [
    /* --- 1. 宿題・提出物（締切順） --- */

    {id:'math-equation-resubmit-sep16',cat:'hw',date:'2026-09-17',dateLabel:'9/17 (木) 20:00 まで',subject:'数学',title:'抜粋プリントNo.1・2 再提出',
      details:['再提出期限は9/17(木) 20:00'],
      thread:'82回生',poster:'山口朋子',posted:'9/16',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1MzE2MDA2NTY4'},
    {id:'loilo-science-sedimentary12',cat:'hw',date:'2026-09-18',dateLabel:'9/18 (金) 17:33 まで',subject:'理科2分野',title:'堆積岩No.12 提出',
      details:[],thread:'ロイロ',poster:''},
    {id:'october-festival-shift-sep19',cat:'hw',date:'2026-09-19',dateLabel:'9/19 (土) 朝まで【十月祭学年担当者へ】',subject:'全体',title:'十月祭 当日シフト希望表の提出',
      details:['当日のシフト希望表を、9/19(土)の朝までに6組のクラスボックスへ提出'],
      thread:'82回生',poster:'大越佳子',posted:'9/18',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1ODA4MTM5NjQw'},
    {id:'gika-sakurabo-sep18',cat:'hw',dateLabel:'次回の授業まで【1・2・3・6組】',subject:'技術家庭',title:'技術・家庭科 サクラボ授業の準備・記事を読む宿題',
      details:['次回もサクラボで授業を実施','iPad、教科書、ファイル、筆記用具をマイバッグ等にまとめて持参','添付記事を読んでくる'],
      thread:'82回生',poster:'菊池菜々世',posted:'9/18',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0Njc1NDIzODEw'},
    {id:'eng-myhero1',cat:'hw',date:'2026-09-28',dateLabel:'9/28 (月) PBE授業内',subject:'英語',title:'My Hero 作品（ロイロカード）提出',
      details:['ワークシートを使って、自分のヒーローを紹介する英文を作成','ロイロカードをPBE授業内で提出','全員分を十月祭で展示予定'],
      thread:'英語',poster:'本木綾子',posted:'9/14',url:'https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/m/ODg0Njk1NTg2ODkx/details'},
    /* --- 2. 連絡事項（日付順） --- */
    {id:'otoshimono1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'落とし物の展示について',
      details:['生徒玄関前に今年度の落とし物を展示中','終業式までに取りに来ないものは夏休み中に処分','貴重品は校務センターで預かり中(同じく終業式まで)'],thread:'82回生',poster:'西出春菜',posted:'7/10',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODcwNDQzMzk2OTMy'},
    {id:'hokendayori1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'保健だよりNo.3【資料】',
      details:['健康手帳・デジタルデトックス・校外授業・睡眠時間について'],thread:'82回生',poster:'西田早苗',posted:'7/10',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODcwMzgwOTIwNzk2/details'},
    {id:'orc1',cat:'no',dateLabel:'当面の間',subject:'英語',title:'Oxford Reading Club トライアル案内',
      details:['サイトでユーザーID/パスワードでログイン→「コードを入力」','トライアルコード: ORCLAURA2026'],thread:'英語',poster:'本木綾子',posted:'7/10',url:'https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODU1NDkxMTQzMzgx'},
    {id:'engmat2',cat:'no',dateLabel:'当面の間',subject:'英語',title:'Oxford Reading Club【資料】',
      details:[],thread:'英語',poster:'本木綾子',posted:'7/7',url:'https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/m/ODcwMzE0OTc3MjM4/details'},
    {id:'engtest1',cat:'no',dateLabel:'当面の間',subject:'英語',title:'英語 夏休み明けテスト範囲',
      details:['新中学問題集6〜8章すべて','ウイニングサマー 文章問題すべて（ただし8章は除く）・単語も出題'],
      thread:'82回生',poster:'本木綾子',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc2NTE0Njk1NTY4'},
    {id:'engtest2',cat:'no',dateLabel:'当面の間',subject:'英語',title:'夏休み明けテスト 模範解答【資料】',
      details:['休み明けテストの模範解答PDFを配信'],
      thread:'英語',poster:'平岡裕子',posted:'9/15',url:'https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/m/ODg0ODU5NTg0MzE1/details'},
    {id:'eng5',cat:'no',dateLabel:'当面の間',subject:'英語',title:'夏休みの注意事項（英語科より）',
      details:['夏休み明けテスト：ウイニングサマー各単元の「この夏おぼえる単語」から10〜20個をスペル（英語）で覚える','Oxford Big Readコンテスト応募希望者：LL教室に画用紙あり（読んだ本のポスターを描いて応募）','Oxford Reading Clubマンスリーレポート：学習状況ページをスクショしてロイロの提出箱に提出'],
      thread:'82回生',poster:'本木綾子',posted:'7/17',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/Nzk4NDYyMzkyMjIy'},
    {id:'jpndblw1',cat:'no',dateLabel:'当面の間',subject:'国語ダブル',title:'1学期国語Wテスト採点基準（ロイロ資料箱）',
      details:['テストの振り返り・解説スライドをロイロの資料箱に配信中','自分の解答と比較して次のテストに活かす'],
      thread:'国語',poster:'西出春菜',posted:'7/11',url:'https://classroom.google.com/c/ODY0MDgzNTIwNTQ5/p/ODcwNDk4ODc4NzMw'},
    {id:'jpndblw2',cat:'no',dateLabel:'当面の間',subject:'国語ダブル',title:'国語ダブル宿題は集めません',
      details:['自分の作品ファイルに綴じておく','初回授業でチェック'],
      thread:'82回生',poster:'西出春菜',posted:'9/4',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc3NTgzMjc4MTc0'},
    {id:'hc1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'健康診断の結果配布',
      details:['4/25実施分の個人結果を担任経由で配布中','フォロー健診の結果配布は後日','受診報告は速やかに保健室へ提出'],thread:'82回生',poster:'西田早苗',posted:'6/16'},
    {id:'hc3',cat:'no',dateLabel:'当面の間',optional:true,subject:'保健',title:'アナフィラキシー親子のための懇談会（神奈川県後援）',
      details:['アナフィラキシーのある親子向け懇談会（神奈川県後援）','参加希望の場合はClassroom添付資料を確認のうえ主催者に直接申込み'],
      thread:'82回生',poster:'西田早苗',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc2NTE0ODY1MzI4'},
    {id:'hc2',cat:'no',dateLabel:'当面の間',subject:'保健',title:'健康手帳回収（始業式）',
      details:['始業式に健康手帳を回収','保健だよりを参照して必要事項の確認・記入・捺印の上、担任に提出','始業式に出せなかった人は保健室に直接提出'],
      thread:'82回生',poster:'西田早苗',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODU2MDU2MDI1Mjgx'},
    {id:'jwu1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'中学生と作る！クロスサイエンス 健康づくりプロジェクト',
      details:['日本女子大学食科学部と連携し骨量・体組成を測定するプログラム（任意参加・無料）','9/9・10・11・24・25の昼休みと放課後、本館1階ロビー（事務室前）で実施','参加には同意書と食生活アンケートが必要（登校日に書面配布予定）'],
      thread:'82回生',poster:'西田早苗',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc0OTA1NzU2ODEz'},
    {id:'taisoku1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'2学期 身体測定（個別実施）',
      details:['集団ではなく個別に実施','昼休みや放課後など都合の良い時に保健室前で測定し、記録用紙を保健室に提出','結果は健康手帳に転記'],
      thread:'82回生',poster:'西田早苗',posted:'9/4',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc1NDY3MDE3MTUz'},
    {id:'sc1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'スタディコモンズ利用者が多いときの注意',
      details:['テスト前は利用者が増加。溢れた場合は1年1・2組の普通教室も活用（メンター指示に従う）','17:40以降はスタコモ部屋に移動','退室時：机・椅子を元の位置に戻す／消しカスをゴミ箱へ／机の中に忘れ物なし'],
      thread:'82回生',poster:'國澤恒久',posted:'6/25',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODU1MzAxNjI0OTM5/details'},
    {id:'u3',cat:'no',dateLabel:'当面の間',subject:'全体',title:'お昼休みのルール制限',
      details:['カラス出没のため、4階屋上での昼食は禁止'],thread:'82回生',poster:'大越佳子',posted:'6/9'},
    {id:'jig1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'実業部の営業日（7・8月）について',
      details:['実業部を利用する際は営業日・営業時間を確認'],thread:'82回生',poster:'宮地潤子',posted:'7/6',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODU1NDI1OTc4MjI5'},
    {id:'jig2',cat:'no',dateLabel:'当面の間',subject:'全体',title:'実業部開室日程（9月）・コート予約販売',
      details:['9月の実業部開室日程・コートの予約販売案内。Classroom添付PDFで確認を（保護者と一緒に）'],
      thread:'82回生',poster:'宮地潤子',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODY5MzEyOTk5ODEz/details'},
    {id:'cal9',cat:'no',dateLabel:'当面の間',subject:'全体',title:'9月カレンダー【資料】',
      details:['9月のスタディコモンズカレンダーを配信。教室にも掲示'],
      thread:'82回生',poster:'國澤恒久',posted:'9/4',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODc3NTUxNTUyNjYz/details'},
    {id:'sekichu1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'脊柱そくわん検査（モアレ検査）10/1実施',
      details:['10/1(木) 13:00〜15:30 講堂北ホールで実施（クラスごと・詳細時間は後日連絡）','1年生全員対象。既に医療機関で受診・治療中の人は不要（連絡簿に記載し担任へ提出）'],
      thread:'82回生',poster:'西田早苗',posted:'9/8',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODcyNzU4ODU2Mzg1'},
    {id:'bijutsu1',cat:'no',dateLabel:'当面の間',subject:'美術',title:'美術 2学期初回授業（持ち物案内）',
      details:['「私の木」版画の続きを実施。1学期と同じ持ち物を持参','持ち物: 絵の具セット(アキーラ・筆必須)、iPad、割烹着、クロッキー帳、筆記用具','アキーラの色が少ない人は早めに買い足しを'],
      thread:'82回生',poster:'芝咲耶子',posted:'9/8',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODY5NDk5MDg1NjY0'},
    {id:'jikugai1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'十月祭5日間の流れ【資料】',
      details:['保護者あて配付の十月祭お知らせと合わせて確認を','印刷したものは今月末の「十月祭諸注意の会」で配付予定'],
      thread:'82回生',poster:'中尾有子',posted:'9/8',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc1NzExNzczMDE3'},
    {id:'gika1',cat:'no',dateLabel:'当面の間',subject:'技術家庭',title:'技術・家庭科より（刺繍キット・今週の授業）',
      details:['宿題の刺繍キット：ロイロで返却があった人は授業初日の作品提出までに直す','今週の授業はサクラボで技術分野','持ち物: iPad(充電必須)、三角巾、刺繍キット、ファイル、技術の教科書、筆記用具（エコバッグ推奨）'],
      thread:'82回生',poster:'菊池菜々世',posted:'9/7',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODY5NDU0NTQxMTc0'},

    {id:'sugaku_kyoshitsu1',cat:'no',dateLabel:'当面の間',subject:'数学',title:'数学ダブル 教室入れ替え（2学期）',
      details:['2学期のダブル授業の教室は1学期と逆に変更','前半クラス: 数学メディア／後半クラス: ホームルーム（座席順は変更なし）'],
      thread:'82回生',poster:'山口朋子',posted:'9/9',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc4NDEwNzczMDgw'},
    {id:'toshoiin1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'図書委員へ：曜日決定・仕事開始',
      details:['明日から仕事開始','ロイロノートに送付されたカードを確認'],
      thread:'82回生',poster:'久保文香',posted:'9/9',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODY5NTI1ODgxMTg1'},
    {id:'seikatsu1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'各クラス生活部部長へ：清掃方法の伝達',
      details:['本日の終礼・自治の会で伝えた清掃方法を教室で伝達','特にごみの捨て方に注意'],
      thread:'82回生',poster:'西出春菜',posted:'9/9',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc4MTUyMjM5ODA5'},
    {id:'seikatsu2',cat:'no',date:'2026-09-11',dateLabel:'9/11 (金)【生活部部長へ】',subject:'全体',title:'本日は臨時清掃',
      details:['クラスに清掃当番を発表','教室当番は廊下まで清掃するよう伝達'],
      thread:'82回生',poster:'西出春菜',posted:'9/11',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc1NTQ4MTA4MDYx'},
    {id:'zkai1',cat:'no',date:'2026-10-07',dateLabel:'10/7 (水) まで【希望者のみ】',optional:true,subject:'英語',title:'Z会 英語ライティング講座のお知らせ',
      details:['学校専用講座で英作文添削を2回受けられる（個人申込不可）','英検合格・スコアアップを目指す人向け。本日終礼でチラシ配布'],
      thread:'82回生',poster:'中尾有子',posted:'9/9',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODcyODMzNDE5ODM0'},
    {id:'gakunen_corner1',cat:'no',date:'2026-09-11',dateLabel:'9/11 (金) 昼休み〜 400【対象者へ】',subject:'全体',title:'十月祭 学年コーナー打ち合わせ',
      details:['対象: 1学期全校委員・2学期全校委員・軽井沢委員・クラブ無所属の人','昼食持参で400教室に集合'],
      thread:'82回生',poster:'大越佳子',posted:'9/9',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc4MTkyMzM0OTE3'},
    {id:'ticket2',cat:'no',date:'2026-09-17',dateLabel:'9/17 (木) まで',subject:'全体',title:'十月祭 第2回チケット・ポスター申請',
      details:['申請フォームより。チケットは渡す相手が決まっている場合のみ','1回目申請済みの人は委員からチケットを受け取り'],
      thread:'82回生',poster:'中尾有子',posted:'9/9',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODU2MTE2MTIxMzc3'},
    {id:'taiiku2',cat:'no',dateLabel:'当面の間',subject:'体育',title:'2学期の体育（石井先生クラス）は中間テストまで保健',
      details:['これまでのプリント・教科書を持参'],
      thread:'82回生',poster:'石井靖子',posted:'9/9',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc4NDE2MDQzMzg5'},
    {"id":"mathres1","cat":"no","dateLabel":"当面の間","subject":"数学","title":"完成ノート3章1次方程式の利用【資料】","details":["抜粋問題・解答のPDFを配信"],"thread":"数学","poster":"森本奈央","posted":"9/8","url":"https://classroom.google.com/c/ODQ5MzY4MjU2Mzg0/m/ODc3ODQ2ODI0NDA4/details"},
    {"id":"mathres2","cat":"no","dateLabel":"当面の間","subject":"数学","title":"1次方程式の利用もっと（１）【資料】","details":["演習プリント・解答のPDFを配信"],"thread":"数学","poster":"森本奈央","posted":"9/10","url":"https://classroom.google.com/c/ODQ5MzY4MjU2Mzg0/m/ODc3ODQ2OTY2MzA2/details"},
    {id:'bball5',cat:'no',date:'2026-09-19',dateLabel:'9/19 (土)・9/20 (日)',subject:'部活',title:'川崎市総体（3年生最後の公式戦・1年生は参加なし）',
      details:['9/19(土)1回戦: 東橘中と対戦、武蔵新城駅8:05集合、10:00トスアップ','9/20(日)2回戦: 南菅中にて、正門前7:30集合、8:45トスアップ','保護者観戦可。1年生は「ようこそ先輩」があるため参加不可'],
      thread:'バスケ',poster:'山本昂宏',posted:'9/10',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/p/ODcyODIxMDg0ODYx'},
    {id:'bball7',cat:'no',date:'2026-10-04',dateLabel:'10/4 (日) 7:35 集合',subject:'部活',title:'北地区シード決め大会（1・2年生）',
      details:['はるひ野駅改札前に7:35集合。会場ははるひ野中','8:50トスアップ（菅中戦）。最低2試合、最高3試合。解散は12:30頃予定','ユニフォームはリバーシブル。保護者観戦なし'],
      thread:'バスケ',poster:'山本昂宏',posted:'9/17',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/p/ODg1NTU0NDU1MDAx'},
    {id:'bball6',cat:'no',date:'2026-09-12',dateLabel:'9/12 (土) 12:00〜',subject:'部活',title:'練習試合（麻生中・田島中）',
      details:['対戦相手: 麻生中(準優勝校)・田島中(ベスト8)。会場: 日本女子','12時には体育館で準備','2年生は東北直前のため無理せず（欠席推奨）'],
      thread:'バスケ',poster:'山本昂宏',posted:'9/10',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/p/ODg0MjE1NTAwMDU2'},
    {id:'engoc2',cat:'no',date:'2026-09-11',dateLabel:'9/11 (金)【英会話 1/2/3組】',subject:'英語',title:'英会話 OC授業（本日実施）持ち物案内',
      details:['持ち物: iPad、Show and Tellスピーチ原稿、クリアファイル、筆箱','前半(出席1-20番): LL教室／後半(21-42番): 400教室','内容: スピーキング活動、スピーチ練習（発表は次回レッスン）'],
      thread:'82回生',poster:'Matthew Collins',posted:'9/10',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODcyNzk0ODM4NDUx'},
    {id:'kokugo1',cat:'no',date:'2026-09-11',dateLabel:'9/11 (金)【国語 1,2,3組】',subject:'国語',title:'国語(秦野) 2学期初回は文法の授業',
      details:['テキスト「つまずかない！文法の学習」とノートを持参'],
      thread:'82回生',poster:'附属中学校伝達用',posted:'9/10',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc2OTc3MDI4MDkw'},
    {id:'tt4',cat:'no',dateLabel:'当面の間',subject:'全体',title:'9/14〜 時間割表（西洋美術館見学・英語ワークショップ等）【資料】',
      details:['第2学期の平常時間割表（1学年 全クラス分）','9/15夕方〜9/16・9/17にかけて「英語ワークショップ」と「国立西洋美術館見学」がクラス間でローテーション。9/18は5-6限に礼法（大ホール）','上の時間割セクションに3組分を反映（木曜のローテーション割当は資料からの推測のため、詳細はリンク先PDFで確認を）'],
      thread:'82回生',poster:'松本珠希',posted:'9/11',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODg0NDc3MDk4OTk5/details'},
    {"id":"tosho2","cat":"no","dateLabel":"9/14〜9/17","subject":"全体","title":"図書室 臨時開館時間（9/14〜17）","details":["9/14(月)〜17(木)は臨時の時間で開館","入室可能時間: 8時20分から／閉館時間: 17時"],"thread":"82回生","poster":"久保文香","posted":"9/11","url":"https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0NTA0ODQ3NjU1","date":"2026-09-17"},
    {id:'moshi1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'日曜日は本校で模試実施（生徒玄関整理のお願い）',
      details:['4階は試験会場ではないが、下校時は生徒玄関の整理整頓を','靴は下足箱にきちんと入れ、靴以外の私物は置かない'],
      thread:'82回生',poster:'國澤恒久',posted:'9/11',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0MjU5ODc4OTA3'},
    {id:'showtell1',cat:'no',date:'2026-09-18',dateLabel:'9/18 (金)【英会話 1/2/3組】',subject:'英語',title:'英会話 Show and Tellスピーチ発表',
      details:['9/18(金)の授業でShow and Tellスピーチを発表','自宅で練習し、清書用紙（final draft）を持参'],
      thread:'82回生',poster:'Matthew Collins',posted:'9/11',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0NDc0NDY1MjU0'},
    {"id":"soumu4","cat":"no","date":"2026-09-21","dateLabel":"9/21 (月) まで【希望者のみ】","optional":true,"subject":"全体","title":"2学期 総務サポーターズ募集","details":["活動は不定期。協力できる人はフォームから申し込みを","代表委員会議事録（配布分）は全校委員が下線部と「8.総務から」を読み上げ"],"thread":"82回生","poster":"山本昂宏","posted":"9/11","url":"https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0NDgyMTM2OTk0","hasLink":true},
    {id:'suiei1',cat:'no',date:'2026-09-14',dateLabel:'9/14 (月)〜',subject:'体育',title:'2学期 水泳の授業が開始',
      details:['忘れ物のないように準備を','見学の場合も体操着に着替える','「水泳の授業について」のプリントを再確認'],
      thread:'82回生',poster:'佐々木樹璃',posted:'9/11',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0MTUxNDQzODY1'},
    {id:'engpbe1',cat:'no',date:'2026-09-14',dateLabel:'9/14 (月)',subject:'英語',title:'英語PBE、教科書持参',
      details:['9/14(月)の授業で教科書を使用するため持参'],
      thread:'82回生',poster:'本木綾子',posted:'9/11',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0NDM4OTg1ODIy'},
    {id:'cal7',cat:'no',dateLabel:'当面の間',subject:'全体',title:'7月カレンダー【資料】',
      details:[],thread:'82回生',poster:'國澤恒久',posted:'6/30',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/Nzk4MzUwNTg4NDY5/details'},
    {id:'n7',cat:'no',dateLabel:'夏休み',optional:true,subject:'課外活動',title:'労働の未来会議2026（中高生向け社会学習）',
      details:['プレゼン・コンテストや企業訪問ができるイベント','締切など詳細は配布PDF／メール連絡網を確認','保護者と相談して参加を検討'],thread:'82回生',poster:'國澤恒久',posted:'6/8'},
    {id:'soumu3',cat:'no',dateLabel:'当面の間',subject:'全体',title:'総務サポーターズ 1学期振り返りアンケート',
      details:['1学期間のサポーターズ活動への感謝とアンケート依頼。2学期も再募集予定','フォームリンクはClassroomの投稿から確認'],
      thread:'総務',poster:'山本昂宏',posted:'8/31',url:'https://classroom.google.com/c/ODYxMzQ0NDY1OTgx/p/ODcyNDg1NTU3MDA4'},
    {id:'soumu2',cat:'no',dateLabel:'夏休み',optional:true,subject:'課外活動',title:'夏休み総務サポーターズ活動（希望者のみ）',
      details:['十月祭準備や2学期準備のサポート活動（希望者対象）','①事前にフォームを提出、または②参加申込書を持参して当日参加（連絡帳でも可）'],
      thread:'総務',poster:'山本昂宏',posted:'7/17',url:'https://classroom.google.com/c/ODYxMzQ0NDY1OTgx/p/Nzk4NDYzODMyMjkz'},
    {id:'act1',cat:'no',dateLabel:'夏休み',subject:'全体',title:'夏休み生徒活動日程表（クラブ・委員会等）【資料】',
      details:[],thread:'82回生',poster:'斉当かおり',posted:'7/14',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODcwNjUwOTE5NDQ3/details'},
    {id:'bsched1',cat:'no',dateLabel:'当面の間',subject:'部活',title:'2026年 9〜10月 練習日程表【資料】',
      details:['9/12(土)午後は麻生中・田島中との練習試合（麻生中フルメンバー）。詳細はリンク先PDFで確認を'],
      thread:'バスケ',poster:'山本昂宏',posted:'8/25',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/m/ODc1NzE2NTQ1MDI1/details'},
    {id:'b5',cat:'no',dateLabel:'夏休み',subject:'部活',title:'2026年 私学選手権大会 日程',
      details:['8/22(土)・23(日)・29(土)・30(日)、9/6(日)・13(日)・20(日)・21(月・祝)','予備日: 9/22(火・祝)・23(水・祝)','直前にならないと日程が確定しないことが多いとのこと'],
      thread:'バスケ',poster:'山本昂宏',posted:'6/18',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/p/ODU1MjEzMDI2OTgy'},
    {id:'bmat1',cat:'no',dateLabel:'夏休み',subject:'部活',title:'2026年夏休み予定表【資料】（少し追記）',
      details:['確定版からさらに一部追記されました（詳細はリンク先で確認）'],thread:'バスケ',poster:'山本昂宏',posted:'7/16',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/m/ODcwNzM1MjU1MTIz/details'},
    /* --- 部活（バスケ）：部活を隠すで一括非表示 --- */
    {id:'b4',cat:'no',dateLabel:'常時',subject:'部活',title:'欠席・遅刻連絡のルール',
      details:['休日の欠席・遅刻早退：保護者がメール連絡網（または電話）で連絡','平日練習に私用で出られない：連絡帳で提出','平日練習に学校活動（委員会・補習・再試・面談など）で出られない：口頭で顧問に連絡'],thread:'バスケ',poster:'山本昂宏',posted:'6/5'},
    {id:'mail-Q94ALwMhmu',cat:'no',date:'2026-10-22',dateLabel:'10/22 (木) 開催',subject:'全体',title:'目白キャンパスめぐり・PTA親睦会のお知らせ',
      details:['10月22日（木）開催「目白キャンパスめぐり・PTA親睦会」の案内','参加希望の方はQRコードより申込み（プリントも配布済み）','Classroom(峯岸憲一)でも同内容が共有されています'],
      thread:'',poster:'保護者向けメール',posted:'9/4',mail:true,mailUrl:'https://object-storage.tyo2.conoha.io/v1/nc_8bd5c69d2f434c1eb45a209a9092bdeb/y-line-jwu-j-net/Q94ALvKCb3',mailPageUrl:'https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q94ALwMhmu'},
    {id:'mail-Q9HF4mlmSW',cat:'no',date:'2026-09-17',dateLabel:'9/17 (木) 解散済み',subject:'82回生',title:'1・2・3組 国立西洋美術館見学 解散連絡',
      details:['国立西洋美術館の見学を終え、15:04に現地解散','館内の作品に加え、晴れ間の中で館外の彫刻も鑑賞'],
      thread:'',poster:'保護者向けメール',posted:'9/17',mail:true,mailPageUrl:'https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q9HF4mlmSW'},
    {id:'mail-Q99IMEuDYr',cat:'no',date:'2026-10-31',dateLabel:'9/11〜10/31 販売期間',subject:'82回生',title:'行事写真インターネット販売のご案内',
      details:['7月の軽井沢三泉寮生活のスナップ写真をサイトで販売','ご希望の方はサイトに登録して購入（お嬢様の写真のみ・SNS等への2次利用不可）','販売期間: 9/11〜10/31'],
      thread:'',poster:'保護者向けメール',posted:'9/9',mail:true,mailUrl:'https://object-storage.tyo2.conoha.io/v1/nc_8bd5c69d2f434c1eb45a209a9092bdeb/y-line-jwu-j-net/Q99IMD05b3',mailPageUrl:'https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q99IMEuDYr'},
    {id:'mail-Q98Jr9S7vT',cat:'no',date:'2026-09-29',dateLabel:'9/29 (火) 14:35〜15:15 大ホール',optional:true,subject:'全体',title:'生徒による朗読会へのお誘い（保護者鑑賞可）',
      details:['広島第一中学校一年生の遺族の手記『星は見ている』の朗読会（生徒会総務主催・生徒のみで上演）','全校生徒で鑑賞。保護者も鑑賞可（大ホール入口の受付へ、保護者証持参）'],
      thread:'',poster:'保護者向けメール',posted:'9/9',mail:true,mailUrl:'https://object-storage.tyo2.conoha.io/v1/nc_8bd5c69d2f434c1eb45a209a9092bdeb/y-line-jwu-j-net/Q998GNFrQo',mailPageUrl:'https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q98Jr9S7vT'},
    {"id":"mail-Q988Sdo1hM","cat":"no","date":"2026-10-12","dateLabel":"10/8〜10/12（一般公開10/10・11）","subject":"全体","title":"十月祭についてのお知らせ","details":["10/8・9は準備。最終下校は8日17:00、9日16:30","一般公開は10/10(土)・11(日) 9:30〜15:30。生徒は8:50出欠確認・16:30最終下校","10/12(月)は片付け・後夜祭。10:00までに片付けを終え、10:15朝礼。1・2年生の最終下校は13:30","5日間とも昼食が必要。10/10・11は生徒の食堂利用不可のため弁当持参","保護者証・配布プログラム・スリッパ・靴袋を持参。保護者と家族は保護者証で入校、一般客は予約またはチケット制","撮影時は保護者証を着用。作品・掲示物の撮影不可。車での来校不可"],"thread":"","poster":"保護者向けメール","posted":"9/8","mail":true,"mailUrl":"https://object-storage.tyo2.conoha.io/v1/nc_8bd5c69d2f434c1eb45a209a9092bdeb/y-line-jwu-j-net/Q988Schtyl","mailPageUrl":"https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q988Sdo1hM"},
    {id:'mail-Q99FEBibC9',cat:'no',dateLabel:'当面の間',subject:'全体',title:'学園ニュースVol.294発行のお知らせ',
      details:['9/10発行。附属校園の特集記事や連載など、閲覧URLを配信','読者アンケートへの協力依頼あり'],
      thread:'',poster:'保護者向けメール',posted:'9/10',mail:true,mailPageUrl:'https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q99FEBibC9'},
    {"id":"mail-Q9ADG4EHcf","cat":"no","dateLabel":"10/10 (土) 12:30〜14:00","subject":"全体","title":"標準服譲り渡しのお知らせ","details":["4階400教室。事前申込みなし・保護者1名のみ入場可","保護者証（忘れると入場不可）、手提げ袋、現金（千円札・小銭）を持参。事前にサイズを確認","整理券40枚を11:00〜11:30に400教室入口で配布（予定数で終了）。入場順は抽選","12:45からフリー入場（12:40から整列可）。売り切れ次第終了","子ども1人につき制服（上着・スカート）1点、その他の物は1点まで。返品・交換不可"],"thread":"","poster":"保護者向けメール","posted":"9/10","mail":true,"mailUrl":"https://object-storage.tyo2.conoha.io/v1/nc_8bd5c69d2f434c1eb45a209a9092bdeb/y-line-jwu-j-net/Q9ADG3Ay18","mailPageUrl":"https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q9ADG4EHcf","date":"2026-10-10","optional":true},
    {"subject":"英語","thread":"英語・ロイロ","poster":"本木綾子","posted":"9/9","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODc4MzgzNzg0NDQ0","hasLink":true,"id":"eng-ch9","cat":"hw","date":"2026-09-24","dateLabel":"9/24 (木) 8:40 まで","title":"新中問 第9章 提出","details":["提出範囲: p.98〜105","ロイロ提出箱で募集中"]},
    {"subject":"英語","thread":"英語","poster":"本木綾子","posted":"9/9","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODc4MzgzNzg0NDQ0","hasLink":true,"id":"eng-ch10","cat":"hw","date":"2026-10-05","dateLabel":"10/5 (月) 8:40 まで","title":"新中問 第10章 提出","details":["提出範囲: p.106〜115"]},
    {"subject":"英語","thread":"英語","poster":"本木綾子","posted":"9/9","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODc4MzgzNzg0NDQ0","hasLink":true,"id":"eng-ch13","cat":"hw","date":"2026-10-19","dateLabel":"10/19 (月) 8:40 まで","title":"新中問 第13章 提出","details":["提出範囲: p.134〜143"]},
    {"subject":"英語","thread":"英語","poster":"本木綾子","posted":"9/9","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODc4MzgzNzg0NDQ0","hasLink":true,"id":"eng-unit6","cat":"no","date":"2026-09-24","dateLabel":"9/24 (木)","title":"英語 Unit 6 テスト","details":["毎回の小テストは行わず、ユニットテストを実施","単語も出題。資料記載の単語範囲はKeyワークp.108・124・138"]},
    {"subject":"英語","thread":"英語","poster":"本木綾子","posted":"9/9","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODc4MzgzNzg0NDQ0","hasLink":true,"id":"eng-unit7","cat":"no","date":"2026-10-06","dateLabel":"10/6（資料の曜日表記に不一致あり）","title":"英語 Unit 7 テスト","details":["毎回の小テストは行わず、ユニットテストを実施","単語も出題。資料記載の単語範囲はKeyワークp.108・124・138","1・2・3組は10/6と記載。資料では月曜となっているが、暦上は火曜のため要確認"]},
    {"subject":"英語","thread":"英語","poster":"本木綾子","posted":"9/9","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODc4MzgzNzg0NDQ0","hasLink":true,"id":"eng-unit8","cat":"no","date":"2026-10-22","dateLabel":"10/22 (木)","title":"英語 Unit 8 テスト","details":["毎回の小テストは行わず、ユニットテストを実施","単語も出題。資料記載の単語範囲はKeyワークp.108・124・138"]},
    {"id":"eng-oc-term2","cat":"no","dateLabel":"当面の間","subject":"英語","title":"OC 2学期予定・Show and Tell評価表","details":["第2回はShow and Tell発表。その後はクラブ紹介、English Firsthand Access Unit 3、ハロウィーン活動、期末試験準備","2学期の評価はShow and Tellと期末試験","スピーチは20点満点: 内容7点・明瞭さ4点・速さとリズム4点・アイコンタクト3点・写真等の視覚資料2点"],"thread":"英語","poster":"Matthew Collins","posted":"9/11","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODc4MTM3ODkyNjM1","hasLink":true},
    {"subject":"英語","thread":"英語","poster":"本木綾子","posted":"9/9","url":"https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/m/ODcyNjkwMzk5MDcz/details","id":"eng-song-sep","cat":"no","dateLabel":"当面の間","title":"I Don't Think That I Like Her【資料】","details":["英語歌詞と日本語訳を掲載した教材PDF"]},
    {id:'eng-workshop-survey',cat:'no',date:'2026-09-16',dateLabel:'9/16 (水) 授業の最初',subject:'英語',title:'英語ワークショップ 事前アンケート',
      details:['授業開始時に事前アンケートを実施'],
      thread:'82回生',poster:'本木綾子',posted:'9/16',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODczMDQ2NTg0NjQ1',hasLink:true},
    {id:'tokyo-u-winter',cat:'no',date:'2026-10-02',dateLabel:'10/2 (金) から【希望者のみ】',optional:true,subject:'英語',title:'東京大学金曜特別講座 冬学期受講案内',
      details:['10/2(金)から冬学期を開始','17:30から自宅でオンライン受講できる人が対象','興味のある人は本木先生へ連絡'],
      thread:'82回生',poster:'本木綾子',posted:'9/15',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1MTAxMDM1MzQ3',hasLink:true},
    {id:'art-repair-sep',cat:'no',date:'2026-09-30',dateLabel:'9/16・9/28・9/30 補修日',subject:'美術',title:'「私の木」版画 補修日',
      details:['2回目の授業までに完成していない、または完成が難しそうな人が対象','9/28(月)は朝・昼のみ'],
      thread:'82回生',poster:'芝咲耶子',posted:'9/15',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODczMDMyOTMxMjcz'},
    {id:'lunch-sep16',cat:'no',date:'2026-09-16',dateLabel:'9/16 (水) 昼休み',subject:'全体',title:'昼休み時間の変更',
      details:['3時間目終了後から昼休み','高校は授業中のため、廊下・共通スペースでは静かに過ごす','4時間目は12:30開始、5時間目以降は通常通り'],
      thread:'82回生',poster:'大越佳子',posted:'9/15',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1MDY1NTgwOTEx'},
    {id:'gakugei-sep16',cat:'no',date:'2026-09-16',dateLabel:'9/16 (水) 12:10 LL【学芸部部長へ】',subject:'全体',title:'学芸部部長 集合（礼法授業の最終確認）',
      details:['12:10にLLへ集合','iPadと筆記用具を持参'],
      thread:'82回生',poster:'大越佳子',posted:'9/15',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1MDUwNjc1MDM1'},
    {id:'eng-gakuryoku-sep',cat:'no',dateLabel:'当面の間',subject:'英語',title:'英語 学力推移調査',
      details:['問題を配布。力試しとして取り組む'],
      thread:'82回生',poster:'本木綾子',posted:'9/15',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg0ODY4OTc5NzY0'},
    {id:'eng-workshop-sep16',cat:'no',date:'2026-09-16',dateLabel:'9/16 (水) 英語ワークショップ',subject:'英語',title:'英語ワークショップ 持ち物・昼休み変更',
      details:['各クラスに外国人講師3名が来校','色を塗れる物（色ペン・色鉛筆・クーピー・クレヨン等）を持参','グループ分け・使用教室は添付表で確認','昼休みは11:40〜12:30に変更'],
      thread:'82回生',poster:'本木綾子',posted:'9/15',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1MDU5ODM0Mjc2',hasLink:true},
    {id:'soumu-welcome-speech-sep16',cat:'no',dateLabel:'当面の間',subject:'全体',title:'ようこそ先輩 グループ会のはじめ・終わりの言葉担当者へ',
      details:['下書きをグループ会担当の先生または担任に確認してもらう','確認後、原稿用紙に清書。原稿用紙は総合委員から受け取る'],
      thread:'82回生',poster:'宮崎可奈子',posted:'9/16',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODczMDQyMTEwODQ5'},
    {id:'kokugo-gakuryoku-sep16',cat:'no',dateLabel:'当面の間',subject:'国語',title:'国語 学力推移調査',
      details:['問題を配布。力試しとして取り組む'],
      thread:'82回生',poster:'鈴木秀一',posted:'9/16',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1MzA5NTA5OTE2'},
    {id:'kokugo-kanji-test-sep29',cat:'hw',date:'2026-09-29',dateLabel:'9/29 (月)【3・4・5・6組】',subject:'国語',title:'国語 漢字豆テスト',
      details:['範囲: ステップ13〜15（P.63〜74）','3組は9/29(月)に実施'],
      thread:'82回生',poster:'鈴木秀一',posted:'9/16',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1Mjk2NTAyMTYy'},
    {id:'eng-workshop-feedback-sep16',cat:'no',date:'2026-09-16',dateLabel:'9/16 (水) 終礼',subject:'英語',title:'英語ワークショップ 振り返りアンケート・学芸部作業',
      details:['参加者アンケートを終礼で実施','学芸部はTシャツの絵を名簿順に並べ、LL教室へ持参','英語の授業でピンクの冊子を再使用するためロッカーに保管'],
      thread:'82回生',poster:'本木綾子',posted:'9/16',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODg1MjkxMDIxMTYz',hasLink:true},
    {id:'math-equation-more1-sep10',cat:'no',dateLabel:'当面の間',subject:'数学',title:'1次方程式の利用もっと（1）【資料】',
      details:[],
      thread:'数学',poster:'森本奈央',posted:'9/10',url:'https://classroom.google.com/c/ODQ5MzY4MjU2Mzg0/m/ODc3ODQ2OTY2MzA2/details'},
    {id:'math-equation-more2-sep16',cat:'no',dateLabel:'当面の間',subject:'数学',title:'1次方程式の利用もっと（2）【資料】',
      details:['演習プリントと解答のPDFを配信'],
      thread:'数学',poster:'森本奈央',posted:'9/16',url:'https://classroom.google.com/c/ODQ5MzY4MjU2Mzg0/m/ODc3ODQyNTE0NDMx/details'},
    {id:'math-equation-test-sep18',cat:'no',dateLabel:'当面の間',subject:'数学',title:'方程式の利用 小テストについて【資料】',
      details:['連休明けの小テストについて、試験範囲のPDFを配信','各自、添付の試験範囲PDFを確認'],
      thread:'数学',poster:'森本奈央',posted:'9/18',url:'https://classroom.google.com/c/ODQ5MzY4MjU2Mzg0/m/ODg1Mzc5NzMzMDY4/details'},
  ]
};
