/* ===== ここだけ毎回貼り替える ===== */
/* updateISO  : New判定・相対日付の基準日 (YYYY-MM-DD)        */
/* updateTime : 更新した時刻 (HH:MM)。曜日は自動で付きます      */
/* timetable  : 週の時間割（PDFから3組のみ抽出）。週次で差し替え */
/* items      : 各行のデータ。Claudeが返す塊をそのまま貼る     */

window.CLASSROOM_DATA = {
  updateISO: "2026-08-31",
  updateTime: "19:47",
  /* timetable: 夏休み中は不要なのでフィールドごと省略（index.htmlはtimetableが無いとセクションごと非表示にする）。
     2学期が始まったら、その週のtimetableをここに復活させる。直前の内容は下のコメントに保存。
  timetable: {
    label: "7/6(月)〜7/10(金)",
    days: [
      {n:'月',md:'7/6',iso:'2026-07-06'},
      {n:'火',md:'7/7',iso:'2026-07-07'},
      {n:'水',md:'7/8',iso:'2026-07-08'},
      {n:'木',md:'7/9',iso:'2026-07-09'},
      {n:'金',md:'7/10',iso:'2026-07-10'},
    ],
    rows: [
      [ {s:'期末テスト',t:'',r:'4日目',rs:6}, {s:'学活',t:'担任',r:'HR'}, {s:'家',t:'菊池',r:'被服B'}, {s:'数',t:'森本',r:'HR'},          {s:'英',t:'本木',r:'HR'} ],
      [ null,                              {s:'学活',t:'担任',r:'HR'}, {s:'学活',t:'担任',r:'HR'}, {s:'国',t:'秋山・西出・秦野',r:'HR'}, {s:'理',t:'大越',r:'HR'} ],
      [ null,                              {s:'学活',t:'担任',r:'HR'}, {s:'国',t:'鈴木',r:'HR'},   {s:'美',t:'芝',r:'美術室'},        {s:'社・理',t:'宮崎・松本',r:'HR'} ],
      [ null,                              {s:'MHC学生交流会',t:'',r:'南ホール'}, {s:'体',t:'石井',r:'HR'}, {s:'軽井沢',t:'担任',r:'HR'}, {s:'軽井沢',t:'担任',r:'HR'} ],
      [ null,                              {s:'音',t:'阿佐美',r:'声楽'}, {s:'学年学活',t:'',r:'大ホール'}, {s:'ようこそ',t:'担任',r:'HR'}, {s:'宿題',t:'菊池',r:'HR'} ],
      [ null,                              {s:'英・社',t:'コリンズ・馬場',r:'HR'}, {s:'ICT',t:'',r:'南ホール'}, {s:'自治の会',t:'',r:'HR'}, {s:'体',t:'押切・新谷',r:'プール'} ],
    ]
  },
  */
  items: [
    /* --- 1. 宿題・提出物（締切順） --- */
    {id:'geo1',cat:'hw',date:'2026-08-31',dateLabel:'8/31 (月) まで',subject:'地理',title:'世界一周すごろく（夏休みの宿題）',
      details:['世界一周すごろくは夏休みの宿題に変更','提出は8月31日の登校日','用紙はテスト返却の授業で配布予定'],
      thread:'82回生',poster:'宮崎可奈子',posted:'7/6',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/Nzk4MzkzMDgyMzYy'},

    /* --- 2. 連絡事項（日付順） --- */
    {id:'otoshimono1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'落とし物の展示について',
      details:['生徒玄関前に今年度の落とし物を展示中','終業式までに取りに来ないものは夏休み中に処分','貴重品は校務センターで預かり中(同じく終業式まで)'],thread:'82回生',poster:'西出春菜',posted:'7/10',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODcwNDQzMzk2OTMy'},
    {id:'hokendayori1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'保健だよりNo.3【資料】',
      details:['健康手帳・デジタルデトックス・校外授業・睡眠時間について'],thread:'82回生',poster:'西田早苗',posted:'7/10',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODcwMzgwOTIwNzk2/details'},
    {id:'orc1',cat:'no',dateLabel:'当面の間',subject:'英語',title:'Oxford Reading Club トライアル案内',
      details:['サイトでユーザーID/パスワードでログイン→「コードを入力」','トライアルコード: ORCLAURA2026'],thread:'英語',poster:'本木綾子',posted:'7/10',url:'https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/p/ODU1NDkxMTQzMzgx'},
    {id:'engmat2',cat:'no',dateLabel:'当面の間',subject:'英語',title:'Oxford Reading Club【資料】',
      details:[],thread:'英語',poster:'本木綾子',posted:'7/7',url:'https://classroom.google.com/c/ODU5Mzk5NTI1NzA5/m/ODcwMzE0OTc3MjM4/details'},
    {id:'engtest1',cat:'no',dateLabel:'当面の間',subject:'英語',title:'英語 夏休み明けテスト範囲',
      details:['新中学問題集6〜8章すべて','ウイニングサマー 文章問題すべて（ただし8章は除く）・単語も出題'],
      thread:'82回生',poster:'本木綾子',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc2NTE0Njk1NTY4'},
    {id:'eng5',cat:'no',dateLabel:'当面の間',subject:'英語',title:'夏休みの注意事項（英語科より）',
      details:['夏休み明けテスト：ウイニングサマー各単元の「この夏おぼえる単語」から10〜20個をスペル（英語）で覚える','Oxford Big Readコンテスト応募希望者：LL教室に画用紙あり（読んだ本のポスターを描いて応募）','Oxford Reading Clubマンスリーレポート：学習状況ページをスクショしてロイロの提出箱に提出'],
      thread:'82回生',poster:'本木綾子',posted:'7/17',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/Nzk4NDYyMzkyMjIy'},
    {id:'jpndblw1',cat:'no',dateLabel:'当面の間',subject:'国語ダブル',title:'1学期国語Wテスト採点基準（ロイロ資料箱）',
      details:['テストの振り返り・解説スライドをロイロの資料箱に配信中','自分の解答と比較して次のテストに活かす'],
      thread:'国語',poster:'西出春菜',posted:'7/11',url:'https://classroom.google.com/c/ODY0MDgzNTIwNTQ5/p/ODcwNDk4ODc4NzMw'},
    {id:'hc1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'健康診断の結果配布',
      details:['4/25実施分の個人結果を担任経由で配布中','フォロー健診の結果配布は後日','受診報告は速やかに保健室へ提出'],thread:'82回生',poster:'西田早苗',posted:'6/16'},
    {id:'hc3',cat:'no',dateLabel:'当面の間',optional:true,subject:'保健',title:'アナフィラキシー親子のための懇談会（神奈川県後援）',
      details:['アナフィラキシーのある親子向け懇談会（神奈川県後援）','参加希望の場合はClassroom添付資料を確認のうえ主催者に直接申込み'],
      thread:'82回生',poster:'西田早苗',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc2NTE0ODY1MzI4'},
    {id:'hc2',cat:'no',dateLabel:'当面の間',subject:'保健',title:'健康手帳回収（始業式）',
      details:['始業式に健康手帳を回収','保健だよりを参照して必要事項の確認・記入・捺印の上、担任に提出','始業式に出せなかった人は保健室に直接提出'],
      thread:'82回生',poster:'西田早苗',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODU2MDU2MDI1Mjgx'},
    {id:'jwu1',cat:'no',dateLabel:'当面の間',subject:'保健',title:'中学生と作る！クロスサイエンス 健康づくりプロジェクト',
      details:['日本女子大学食科学部と連携し骨量・体組成を測定するプログラム（任意参加・無料）','9/9・10・11・24・25の昼休みと放課後、本館1階ロビー（事務室前）で実施','参加には同意書と食生活アンケートが必要（登校日に書面配布予定）'],
      thread:'82回生',poster:'西田早苗',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc0OTA1NzU2ODEz'},
    {id:'sc1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'スタディコモンズ利用者が多いときの注意',
      details:['テスト前は利用者が増加。溢れた場合は1年1・2組の普通教室も活用（メンター指示に従う）','17:40以降はスタコモ部屋に移動','退室時：机・椅子を元の位置に戻す／消しカスをゴミ箱へ／机の中に忘れ物なし'],
      thread:'82回生',poster:'國澤恒久',posted:'6/25',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODU1MzAxNjI0OTM5/details'},
    {id:'u3',cat:'no',dateLabel:'当面の間',subject:'全体',title:'お昼休みのルール制限',
      details:['カラス出没のため、4階屋上での昼食は禁止'],thread:'82回生',poster:'大越佳子',posted:'6/9'},
    {id:'jig1',cat:'no',dateLabel:'当面の間',subject:'全体',title:'実業部の営業日（7・8月）について',
      details:['実業部を利用する際は営業日・営業時間を確認'],thread:'82回生',poster:'宮地潤子',posted:'7/6',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODU1NDI1OTc4MjI5'},
    {id:'jig2',cat:'no',dateLabel:'当面の間',subject:'全体',title:'実業部開室日程（9月）・コート予約販売',
      details:['9月の実業部開室日程・コートの予約販売案内。Classroom添付PDFで確認を（保護者と一緒に）'],
      thread:'82回生',poster:'宮地潤子',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODY5MzEyOTk5ODEz/details'},
    {id:'iinkai1',cat:'no',date:'2026-08-31',dateLabel:'8/31 (月)【総合委員の会】',subject:'全体',title:'ようこそ先輩 総合委員の会（8/31 終礼後・LL教室）',
      details:['終礼後にLL教室にて会を実施。荷物をすべて持って集合'],
      thread:'82回生',poster:'宮崎可奈子',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc2NDYzNzY1MzE3'},
    {id:'jisshi1',cat:'no',date:'2026-08-31',dateLabel:'8/31 (月)【行事委員へ】',subject:'全体',title:'十月祭 行事委員へ：チケット枚数調査',
      details:['チケット6枚以上希望者の調査を本日中に実施するよう連絡','名簿に記録し、2学期最初の自治の会に持参'],
      thread:'82回生',poster:'中尾有子',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc1MjM3OTM5OTE5'},
    {id:'explan1',cat:'no',date:'2026-09-06',dateLabel:'9/6 (日) 学校説明会',subject:'全体',title:'9/6(日) 学校説明会サポーターズ（申込済の方へ）',
      details:['集合は早い係で8:00頃、解散は遅い係で12:30頃の予定','申し込みをした方には始業式の日に説明の会を実施'],
      thread:'82回生',poster:'馬場友紀',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc2NDk4ODE0NDM1'},
    {id:'cal7',cat:'no',dateLabel:'当面の間',subject:'全体',title:'7月カレンダー【資料】',
      details:[],thread:'82回生',poster:'國澤恒久',posted:'6/30',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/Nzk4MzUwNTg4NDY5/details'},
    {id:'keiribu1',cat:'no',date:'2026-09-04',dateLabel:'9/4 (金) 12:20 理科A【経理部部長へ】',subject:'全体',title:'経理部 2学期臨時部長会（9/4）',
      details:['9/4(金) 12:20〜 理科A にて臨時部長会。時間厳守で集合'],
      thread:'82回生',poster:'松本珠希',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc1MzM2NzYxOTA4'},
    {id:'keiri1',cat:'no',date:'2026-09-04',dateLabel:'9/4 (金) まで【希望者のみ】',optional:true,subject:'課外活動',title:'十月祭 経理部チャリティー「マカロン付箋」デザイン募集',
      details:['今年度の十月祭チャリティーは「マカロン付箋」を販売（経理部企画）','全校生徒からデザインを募集（希望者のみ）','添付資料を確認の上、9/4(金)までに提出'],
      thread:'82回生',poster:'松本珠希',posted:'8/31',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/p/ODc1NDY3NjA4MTI3'},
    {id:'n7',cat:'no',dateLabel:'夏休み',optional:true,subject:'課外活動',title:'労働の未来会議2026（中高生向け社会学習）',
      details:['プレゼン・コンテストや企業訪問ができるイベント','締切など詳細は配布PDF／メール連絡網を確認','保護者と相談して参加を検討'],thread:'82回生',poster:'國澤恒久',posted:'6/8'},
    {id:'soumu3',cat:'no',dateLabel:'当面の間',subject:'全体',title:'総務サポーターズ 1学期振り返りアンケート',
      details:['1学期間のサポーターズ活動への感謝とアンケート依頼。2学期も再募集予定','フォームリンクはClassroomの投稿から確認'],
      thread:'総務',poster:'山本昂宏',posted:'8/31',url:'https://classroom.google.com/c/ODYxMzQ0NDY1OTgx/p/ODcyNDg1NTU3MDA4'},
    {id:'soumu2',cat:'no',dateLabel:'夏休み',optional:true,subject:'課外活動',title:'夏休み総務サポーターズ活動（希望者のみ）',
      details:['十月祭準備や2学期準備のサポート活動（希望者対象）','①事前にフォームを提出、または②参加申込書を持参して当日参加（連絡帳でも可）'],
      thread:'総務',poster:'山本昂宏',posted:'7/17',url:'https://classroom.google.com/c/ODYxMzQ0NDY1OTgx/p/Nzk4NDYzODMyMjkz'},
    {id:'act1',cat:'no',dateLabel:'夏休み',subject:'全体',title:'夏休み生徒活動日程表（クラブ・委員会等）【資料】',
      details:[],thread:'82回生',poster:'斉当かおり',posted:'7/14',url:'https://classroom.google.com/c/ODU4NTUxNTUzOTEy/m/ODcwNjUwOTE5NDQ3/details'},
    {id:'bball3',cat:'no',date:'2026-08-30',dateLabel:'8/30 (日) 9:00 トスアップ',subject:'部活',title:'私学大会 第1回戦（日程確定）',
      details:['8/30(日) 会場：横須賀学院','対戦相手：洗足学園 9:00 トスアップ','勝利の場合、12:45から2回戦（その後TOあり）','今後変更の可能性もあり。変更時は追って連絡'],
      thread:'バスケ',poster:'山本昂宏',posted:'8/18',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/p/ODc0OTIyOTI2NjI1'},
    {id:'bsched1',cat:'no',dateLabel:'当面の間',subject:'部活',title:'2026年 9〜10月 練習日程表【資料】',
      details:['9/12(土)午後は麻生中・田島中との練習試合（麻生中フルメンバー）。詳細はリンク先PDFで確認を'],
      thread:'バスケ',poster:'山本昂宏',posted:'8/25',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/m/ODc1NzE2NTQ1MDI1/details'},
    {id:'b5',cat:'no',dateLabel:'夏休み',subject:'部活',title:'2026年 私学選手権大会 日程',
      details:['8/22(土)・23(日)・29(土)・30(日)、9/6(日)・13(日)・20(日)・21(月・祝)','予備日: 9/22(火・祝)・23(水・祝)','直前にならないと日程が確定しないことが多いとのこと'],
      thread:'バスケ',poster:'山本昂宏',posted:'6/18',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/p/ODU1MjEzMDI2OTgy'},
    {id:'bmat1',cat:'no',dateLabel:'夏休み',subject:'部活',title:'2026年夏休み予定表【資料】（少し追記）',
      details:['確定版からさらに一部追記されました（詳細はリンク先で確認）'],thread:'バスケ',poster:'山本昂宏',posted:'7/16',url:'https://classroom.google.com/c/MzI3NTczNzQyMTQy/m/ODcwNzM1MjU1MTIz/details'},
    /* --- 部活（バスケ）：部活を隠すで一括非表示 --- */
    {id:'b4',cat:'no',dateLabel:'常時',subject:'部活',title:'欠席・遅刻連絡のルール',
      details:['休日の欠席・遅刻早退：保護者がメール連絡網（または電話）で連絡','平日練習に私用で出られない：連絡帳で提出','平日練習に学校活動（委員会・補習・再試・面談など）で出られない：口頭で顧問に連絡'],thread:'バスケ',poster:'山本昂宏',posted:'6/5'},
    {id:'mail-Q8TEI5uYC4',cat:'no',date:'2026-08-29',dateLabel:'8/29 (土)',subject:'全体',title:'登校時間帯の不審者について',
      details:['読売ランド前駅からの通学路で不審者事案が複数回発生（8時前〜9時半、単独歩行中の生徒に話しかけ・身体接触）','多摩警察署に通報・警戒強化中。学校警備員も立哨・巡回中','登下校時はできるだけ複数人で歩くこと。不審者を見かけたら警察官・警備員または担任に報告を'],
      thread:'',poster:'保護者向けメール',posted:'8/29',mail:true,mailPageUrl:'https://www.y.line-nt.com/linenet/member/jwu-j-net/Q2INSF1UQi/mail/Q8TEI5uYC4'},
  ]
};
